discord_emojis = [
    ":grinning:", ":smiley:", ":smile:", ":grin:", ":laughing:", ":sweat_smile:", 
    ":rofl:", ":joy:", ":slightly_smiling_face:", ":upside_down_face:", ":wink:", 
    ":blush:", ":innocent:", ":heart_eyes:", ":star_struck:", ":kissing_heart:", 
    ":kissing:", ":relaxed:", ":kissing_closed_eyes:", ":kissing_smiling_eyes:", 
    ":yum:", ":stuck_out_tongue:", ":stuck_out_tongue_winking_eye:", 
    ":stuck_out_tongue_closed_eyes:", ":money_mouth_face:", ":hugs:", 
    ":face_with_hand_over_mouth:", ":shushing_face:", ":thinking:", ":zipper_mouth_face:",
    ":face_with_raised_eyebrow:", ":neutral_face:", ":expressionless:", 
    ":no_mouth:", ":smirk:", ":unamused:", ":roll_eyes:", ":grimacing:", 
    ":face_exhaling:", ":lying_face:", ":relieved:", ":pensive:", ":sleepy:", 
    ":drooling_face:", ":sleeping:", ":mask:", ":face_with_thermometer:", 
    ":face_with_head_bandage:", ":nauseated_face:", ":vomiting_face:", 
    ":sneezing_face:", ":hot_face:", ":cold_face:", ":woozy_face:", ":dizzy_face:",
    ":exploding_head:", ":cowboy_hat_face:", ":partying_face:", ":sunglasses:",
    ":nerd_face:", ":monocle_face:", ":confused:", ":worried:", ":slightly_frowning_face:", 
    ":frowning_face:", ":open_mouth:", ":hushed:", ":astonished:", ":flushed:", 
    ":pleading_face:", ":frowning:", ":anguished:", ":fearful:", ":cold_sweat:", 
    ":disappointed_relieved:", ":cry:", ":sob:", ":scream:", ":confounded:", 
    ":persevere:", ":disappointed:", ":sweat:", ":weary:", ":tired_face:", 
    ":yawning_face:", ":triumph:", ":rage:", ":angry:", ":cursing_face:", 
    ":smiling_imp:", ":imp:", ":skull:", ":ghost:", ":alien:", ":space_invader:", 
    ":robot:", ":jack_o_lantern:", ":clown_face:", ":pregnant_man:"
]
